### PR TITLE
Multi templating and a basic CentOS theme

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by ralphbean** [comment]
Cool cool.

- I saw flask multistatic has its own repo on pagure now?
- Is it going to be released to pypi and packaged?
- If so, can we not bundle it here but just include it instead?

**Comment by pypingou** [comment]
On Tue, Jul 28, 2015 at 06:46:04AM -0700, Ralph Bean wrote:
>    Cool cool.
> 
>      * I saw flask multistatic has its own repo on pagure now?

True :)

>      * Is it going to be released to pypi and packaged?

At one point yes

>      * If so, can we not bundle it here but just include it instead?

That might be the best way. I wanted to bundle it here to test it and see how it
works in prod but on the other end if it doesn't work as expected/desired it
will be easier to drop if we don't bundle it.

**Comment by ralphbean** [comment]
Cool, well, :+1: either way.  It can be unbundled later.

**Comment by pypingou** [comment]
I'm getting lazy, since you :+1: I'll merge and we can see later about unbundling it if it works as desired :)

Thanks!

**Pull request merged**
